# Generated by Django 3.1.7 on 2021-10-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='mydoc')),
                ('doc_type', models.CharField(choices=[('citizenship', 'citizenship'), ('Driving-License', 'Driving-License'), ('Passport', 'Passport')], max_length=30)),
                ('valid_doc', models.ImageField(upload_to='mydoc')),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=60)),
                ('verified', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=35)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pro_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='products')),
                ('base_price', models.FloatField()),
                ('category', models.CharField(choices=[('jewelry', 'jewelry'), ('vehicle', 'vehicle'), ('sports', 'sports'), ('real state', 'real state'), ('electronics', 'electronics'), ('others', 'others')], max_length=30)),
                ('status', models.CharField(choices=[('notSpecified', 'not specified'), ('onAuction', 'on auction'), ('sold', 'sold'), ('unsold', 'unsold')], max_length=25)),
                ('verified', models.BooleanField(default=False)),
                ('auction_start', models.DateTimeField()),
                ('auction_expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('bidding_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('current_price', models.FloatField()),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('updated_price', models.FloatField()),
                ('pro', models.ManyToManyField(to='myapp.product')),
                ('username', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
