# Generated by Django 3.1.7 on 2021-10-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211004_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='bid',
            field=models.ManyToManyField(to='myapp.product'),
        ),
        migrations.DeleteModel(
            name='bidding',
        ),
    ]
