# Generated by Django 3.1.7 on 2021-10-05 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20211005_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='bid',
        ),
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('bidding_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('current_price', models.FloatField()),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('updated_price', models.FloatField()),
                ('pro', models.ManyToManyField(to='myapp.product')),
                ('username', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
