# Generated by Django 3.1.7 on 2021-10-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211005_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='pro',
            new_name='product',
        ),
    ]
