# Generated by Django 3.1.7 on 2021-10-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211005_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bidding_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
