# Generated by Django 3.1.7 on 2021-10-05 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_delete_bidding'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField()),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('updated_price', models.FloatField()),
                ('product', models.ManyToManyField(to='myapp.product')),
                ('username', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
