# Generated by Django 3.1.7 on 2021-10-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bids',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
