# Generated by Django 3.1.7 on 2021-10-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20211006_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_img',
            field=models.ImageField(default='profile.png', upload_to='mydoc'),
        ),
    ]
